# Generated by Django 4.2.7 on 2023-11-25 09:53

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beekeepers',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('beekeeper_id', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Hives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=255)),
                ('treatment', models.CharField(max_length=255)),
                ('mite_drop', models.IntegerField()),
                ('condition', models.IntegerField()),
                ('honey_amount', models.FloatField()),
                ('zootechnical_act', models.CharField(max_length=255)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hives')),
            ],
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('performance', models.CharField(max_length=255)),
                ('male_line', models.CharField(max_length=255)),
                ('female_line', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('hive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.hives')),
            ],
        ),
        migrations.CreateModel(
            name='HivesPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('beekeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beekeepers')),
            ],
        ),
        migrations.AddField(
            model_name='hives',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hivesplace'),
        ),
    ]
