# Generated by Django 4.2.7 on 2023-11-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HivesPlace',
            new_name='HivesPlaces',
        ),
    ]
