# Generated by Django 4.2.7 on 2023-11-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_hivesplace_hivesplaces'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visit',
            new_name='Visits',
        ),
    ]
