# Generated by Django 4.2.7 on 2023-12-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_visit_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='mother',
            name='mark',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
