# Generated by Django 4.2.7 on 2023-12-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_mother_mark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mother',
            new_name='Mothers',
        ),
    ]
