# Generated by Django 4.2.7 on 2023-12-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_mother_mothers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mothers',
            name='mark',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
