# Generated by Django 4.2.7 on 2023-12-01 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_mothers_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mothers',
            name='ancestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.mothers'),
        ),
    ]
