# Generated by Django 4.2.7 on 2023-12-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_mothers_ancestor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='visits',
            name='hive',
        ),
        migrations.RemoveField(
            model_name='visits',
            name='honey_amount',
        ),
        migrations.RemoveField(
            model_name='visits',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='visits',
            name='type',
        ),
        migrations.RemoveField(
            model_name='visits',
            name='zootechnical_act',
        ),
        migrations.AddField(
            model_name='visits',
            name='disease',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visits',
            name='hive_body_size',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visits',
            name='honey_supers_size',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visits',
            name='honey_yield',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visits',
            name='inspection_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visits',
            name='medication_application',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visits',
            name='performed_tasks',
            field=models.ManyToManyField(blank=True, to='myapp.tasks'),
        ),
    ]
