# Generated by Django 4.2.7 on 2023-12-02 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_tasks_remove_visits_hive_remove_visits_honey_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mothers',
            name='performance',
        ),
    ]
